In [1]:
#Answer_1

import numpy as n
arr = n.random.random((10, 1))
m=n.mean(arr)
print("The array is:\n{}\n The Mean is:{}".format(arr,m))

The array is:
[[0.13979439]
 [0.34182531]
 [0.16928941]
 [0.16011488]
 [0.22710885]
 [0.51322717]
 [0.16593811]
 [0.11173529]
 [0.75789611]
 [0.78724053]]
 The Mean is:0.3374170053203086


In [2]:
#Answer_2

import numpy as n
array = n.random.random((20, 1))
s=n.std(array)
new=s**2
print("The array is:\n{}\n The Variance is:{}\n The Standard Deviation is:{}".format(array,new,s))


The array is:
[[0.40077912]
 [0.09048894]
 [0.74065476]
 [0.34127034]
 [0.82479163]
 [0.67263075]
 [0.97431392]
 [0.95880295]
 [0.8137643 ]
 [0.9392911 ]
 [0.03659527]
 [0.84144395]
 [0.88337434]
 [0.09444821]
 [0.30377858]
 [0.97944738]
 [0.77704297]
 [0.55968041]
 [0.42882933]
 [0.2229384 ]]
 The Variance is:0.10092965934965321
 The Standard Deviation is:0.31769428598835897


In [3]:
#Answer_3

import numpy as n
A = n.random.random((10,20))
print("Matrix A is: \n",A,"\n")
B = n.random.random((20,25))
print("Matrix B is: \n",B,"\n")
C=n.matmul(A, B)
print("Multiplication of a and B: \n",C,"\n")
print("Sum of elements of C:",n.sum(C))

Matrix A is: 
 [[0.15287943 0.70571426 0.63714042 0.56839416 0.97155722 0.07590257
  0.10115278 0.72972205 0.42569263 0.38935079 0.87346287 0.09096696
  0.0829051  0.00433738 0.2602907  0.84860352 0.05081477 0.33547341
  0.71398931 0.31826152]
 [0.22162792 0.20111183 0.76879823 0.59642884 0.77257011 0.55692546
  0.2454526  0.26816881 0.04530985 0.69235613 0.55513501 0.83767717
  0.21739082 0.1583764  0.49179984 0.7982207  0.77502121 0.87052631
  0.76580993 0.12799404]
 [0.41975766 0.78125298 0.66352856 0.51467794 0.31073905 0.48899649
  0.19393773 0.61845615 0.60966237 0.86655377 0.58200171 0.31508773
  0.00739873 0.50402097 0.54399148 0.59952303 0.96332913 0.37846154
  0.8893824  0.26573573]
 [0.5352347  0.69313402 0.72128292 0.01239887 0.26583324 0.53645133
  0.77152757 0.93214859 0.6692309  0.49781841 0.1393145  0.40452975
  0.33900019 0.27664155 0.94685262 0.89591998 0.29653077 0.11471268
  0.48377146 0.13352558]
 [0.4530768  0.72945692 0.27272143 0.47908901 0.5736801  0.7473286
  

Multiplication of a and B: 
 [[4.03536518 4.45263799 3.78044754 3.10318004 4.74105865 3.1170254
  4.28494779 4.37811291 3.44483159 2.61202424 5.00930628 4.15431219
  4.46457932 4.00628831 3.97184166 3.06653023 3.81978929 3.33455886
  4.41515353 2.93485454 4.70171635 4.7332076  3.56742398 4.82520721
  3.47582344]
 [4.54224911 5.18568792 5.54287144 3.71560224 5.76701074 4.50337411
  5.57303599 5.04187554 4.81138846 2.81076783 6.11647129 5.46444662
  4.97826905 5.35729701 4.04875737 4.95807216 5.36232018 3.49757404
  5.62815251 3.53202669 5.32302225 5.28151873 4.43167856 5.42924869
  4.50603398]
 [5.35826266 5.4998139  5.70787218 3.40450857 5.98587479 4.70078847
  5.90662628 6.07662881 5.52132025 3.51334427 6.72728047 4.75403365
  5.02022622 5.80063873 4.55540334 4.62839266 4.93023624 4.01816719
  5.83814093 4.41777443 5.82830666 6.08204207 5.12019753 5.77241441
  4.64330488]
 [5.24799565 4.88563069 4.31004639 3.22797571 5.24125369 4.69394234
  5.54306509 5.11181995 4.50887859 3.31854344 

In [5]:
#Answer_4
import numpy as n
A = n.random.random((10,1))

print("The original matrix is:\n{}\n".format(A))

def fun(num):
    return (1 / (1 + n.exp(-num)))

m = n.apply_along_axis(fun, 0, A)
print("The result matrix is:\n{}\n".format(m))


The original matrix is:
[[0.55639795]
 [0.30722781]
 [0.67936457]
 [0.78909011]
 [0.27115809]
 [0.07398166]
 [0.6989645 ]
 [0.5690892 ]
 [0.88737731]
 [0.07385985]]

The result matrix is:
[[0.63561869]
 [0.57620846]
 [0.66359686]
 [0.68763593]
 [0.56737719]
 [0.51848698]
 [0.66795815]
 [0.63855299]
 [0.70834865]
 [0.51845657]]

